### PR TITLE
Sanity check for relorder params

### PR DESCRIPTION
**Pull request by abitfan**
Initial sanity checks as per #73

### CODE REVIEW

**Comment by chris-belcher** [comment]
Does anyone remember what was said about negative cj fee ? They'll probably never actually be made but it seems anti-competitive to have a price floor.

Did you test this? oid can be zero (as more are now) as well as negative or positive. It's just a marker for orders because a single maker can have many orders.

minsize, txfee and cjfee can be zero.

minsize could be equal to maxsize

This could should probably be in the OrderbookWatch class https://github.com/chris-belcher/joinmarket/blob/master/lib/taker.py#L201

Those fields are all strings by the way, so integer comparison wont work

**Comment by abitfan** [comment]
It only skips the order if any value is less than 0, they can be zero and it will pass
minsize is checked if its greater than maxsize, so they can be equal
Missed the fact about strings, should be fixed now.

I think we need to do sanity checks before passing the args further, so this seems a good place to add them

**Comment by chris-belcher** [comment]
Ah yes you're right about the zero.

If you add the checks here, they'll have to be copypasted into any new MessageChannel class that gets made. Which is repeating code, the understanding of orders belongs in the OrderbookWatch class not the IRCMessageChannel.

btw, using float() would cause a crash if the string is not parsable as a float. All the other fields are actually integers, cjfee is a float only for relorder, it is an integer for absorder.

**Comment by abitfan** [comment]
Added checks as proposed. There is no restriction on cjfee implemented

**Pull request merged**
