### PR TITLE
Change how random irc nicknames are generated.

### PR DESCRIPTION
**Pull request by CohibAA**
I believe this is a more anonymous and random method and possibly more efficient way to generate random_nick for ircnick.  Thoughts?

### CODE REVIEW

**Comment by CohibAA** [comment]
Forgot to mention, I believe urllib2 may have also been causing an error in tor logs when generating the nickname...

    [warn] Socks version 80 not recognized. (Tor is not an http proxy.)

but I am not 100% sure of the cause of the tor log error, so feedback is appreciated.

**Comment by CohibAA** [comment]
I am not too familiar with restrictions on irc naming, so maybe this still needs to check for naming rules and try again if any violations occur.  What restrictions exist for irc nicknames? Can any digits or letters be the first character?.  I didn't have any issues while testing, but maybe the re.match check should not be removed, or should be modified somehow?

**Comment by chris-belcher** [comment]
I used wikipedia because I thought the english-language words would make it less clear which IRC nick was a bot and which was an actual human. It might be important for a tumbler bot for example which idles in the channel for a long time and never publicly says anything.

**Comment by CohibAA** [comment]
That makes sense, regarding why to use Wikipedia for names.  My primary concern was the call to get the wiki page and urllib2's impact on tor integrity, hence this workaround method.

Regarding urllib2 and tor, [this](https://stackoverflow.com/questions/5148589/python-urllib-over-tor) is likely what caused the tor log warnings.

    The problem is that httplib.HTTPConnection uses the socket module's create_connection helper function which does the DNS request via the usual getaddrinfo method before connecting the socket.

I have not seen the warnings while not using the urllib2 import.  This is the solution suggested on stackflow.

    The solution is to make your own create_connection function and monkey-patch it into the socket module before importing urllib2, just like we do with the socket class.

Suggested code example:

    import socks
    import socket
    def create_connection(address, timeout=None, source_address=None):
        sock = socks.socksocket()
        sock.connect(address)
        return sock
    
    socks.setdefaultproxy(socks.PROXY_TYPE_SOCKS5, "127.0.0.1", 9050)

    # patch the socket module
    socket.socket = socks.socksocket
    socket.create_connection = create_connection
    
    import urllib2

I haven't researched completely nor tested at all, but this looks to fit at first glance.  I will revert to the Wikipedia names method and try this solution to see if the tor warnings stay away.

**Comment by WyseNynja** [comment]
I like this PR.  If someone wants to "hide" in the channel by pretending to be a bot, they can pick some random numbers or letters just as easily as they can pick a random page off wikipedia.  There's no need to make an http request.

**Comment by chris-belcher** [comment]
The http request really kills it actually.
Has anyone tried this yet? I'll merge after trying it.

**Comment by kristovatlas** [comment]
There's python code for connecting to Tor in this script that works, if anyone is interested: https://github.com/kristovatlas/onion-uptime/blob/master/check-onion-status.py

**Comment by tailsjoin** [comment]
I have tried this code and it works fine. It should be merged immediately imo because this unproxied http call is messing things up for Tails while using Bitcoin core. Torify is not a possible solution for my situation either as it will torify rpc calls as well.

**Comment by CohibAA** [comment]
my watcher bot is also using this, no problems

**Comment by chris-belcher** [comment]
Hope not to offend @CohibAA by throwing away his code, but I couldn't resist coming up with a way to produce more pronounceable names. As in https://gist.github.com/chris-belcher/cd51b9edf3465c19c8f1

**Comment by CohibAA** [comment]
No offense!  My main concern was getting away from the http call, however it is accomplished.

**Pull request merged**
