### PR TITLE
Crude recovery by taker from unresponsive makers

### PR DESCRIPTION
**Pull request by chris-belcher**
Implemented changes suggested in #166

A new thread is started for each CoinJoinTX object, there is a threading condition lock which passes notifications between the two threads. Currently the timeout for maker non-reply is 10 seconds.

If a maker doesn't reply, it will be ignored for the rest of lifetime of the Taker instance.

`sendpayment.py` and `tumbler.py` have been made to work with this.

Testing welcome. I've tested this on regtest with tumbler, it was able to complete it's run even though one maker never responded to either !fill, !auth or !tx

Second attempt at merging, given the derping with the other branch.

Please test, especially let me know if you encounter an unresponsive maker. Watch if the taker handles that in the correct manner.

### CODE REVIEW

**Comment by tailsjoin** [comment]
I did a fresh pull of the crude-taker-recovery2 branch, generated a new wallet, and funded the first address. While attempting to tumble or send-payment I crash during the first transaction. I have the entire log if this error message doesn't explain it well enough (I switched branches to master and the tumbler is working fine, so it's definitely the branch):

     File "tumbler.py", line 351, in main
        irc.run()
      File ".../lib/irc.py", line 492, in run
        self.__handle_line(line)
      File ".../lib/irc.py", line 395, in __handle_line
        self.__handle_privmsg(chunks[0], chunks[2], get_irc_text(line))
      File ".../lib/irc.py", line 348, in __handle_privmsg
        self.__on_privmsg(nick, parsed)
      File ".../lib/irc.py", line 232, in __on_privmsg
        self.on_sig(nick, sig)
      File ".../taker.py", line 374, in on_sig
        self.cjtx.add_signature(nick, sig)
      File ".../lib/taker.py", line 161, in add_signature
        self.utxos[nick].remove(utxo)
    ValueError: list.remove(x): x not in list

**Comment by chris-belcher** [comment]
@tailsjoin it seems it's trying to remove a UTXO that isn't in that list. Probably because it's already been removed. Does the debug log show anything useful regarding that?

I'll run the branch again a bit later to try to reproduce the crash.

**Comment by tailsjoin** [comment]
The crash comes always after the finding the first good sig. Here's one of the log dumps:

https://paste.debian.net/plainh/7d543031

**Comment by chris-belcher** [comment]
@tailsjoin 's crash comes from when this feature was merged with the master branch which contained #172. Will fix.

**Comment by chris-belcher** [comment]
Fixed bug, and tried it myself on the mainnet (earlier tests were only on testnet or regtest). Did not try any unresponsive makers, although the -P option of sendpayment might be useful for that.

**Comment by chris-belcher** [comment]
Was talking to someone on IRC who was trying this (on tails) they said they got some crashed.

Fixed crash (which is a dos opportunity if makers can crash a taker), increased default length to 20 seconds. Tested it on mainnet with -P and my own maker.

**Comment by tailsjoin** [comment]
I'm getting this again:

    File "tumbler.py", line 351, in main
      irc.run()
    File "/home/amnesia/joinmarket/lib/irc.py", line 492, in run
      self.__handle_line(line)
    File "/home/amnesia/joinmarket/lib/irc.py", line 395, in __handle_line
      self.__handle_privmsg(chunks[0], chunks[2], get_irc_text(line))
    File "/home/amnesia/joinmarket/lib/irc.py", line 348, in __handle_privmsg
      self.__on_privmsg(nick, parsed)
    File "/home/amnesia/joinmarket/lib/irc.py", line 232, in __on_privmsg
      self.on_sig(nick, sig)
    File "/home/amnesia/joinmarket/lib/taker.py", line 370, in on_sig
      self.cjtx.add_signature(nick, sig)
    File "/home/amnesia/joinmarket/lib/taker.py", line 162, in add_signature
      self.nonrespondants.remove(nick)
    ValueError: list.remove(x): x not in list

    done
    amnesia@amnesia:~/joinmarket$ git pull
    Already up-to-date.
    amnesia@amnesia:~/joinmarket$ git branch
    * crude-taker-recovery2

**Comment by chris-belcher** [comment]
Committed something which I think fixes it, but not sure. Please could you send me the debug log part for that part of the transaction?

Was this the first transaction ever done? I believe it was caused by a race condition so shouldn't happen every time.

If it doesn't work you could try raising the response timeout in joinmarket.cfg (although if there's an underlying bug, this won't fix it just make it less likely)

**Comment by tailsjoin** [comment]
It was the very first tx with a new wallet. I've run it again, and it seems to be going well. Here is the log from the first attempt: https://paste.debian.net/plainh/a69f67bc

**Comment by chris-belcher** [comment]
I haven't been able to decrypt that message, or your new issue opened today.

	gpg: no valid OpenPGP data found.
	gpg: block_filter 0x9d6adb8: read error (size=15871,a->size=15871)
	gpg: encrypted_mdc packet with unknown version 255
	gpg: block_filter: pending bytes!

**Comment by tailsjoin** [comment]
That's strange. I just did `gpg --list-packets` on this links message, and I get:

    :pubkey enc packet: version 3, algo 1, keyid 249C32A6B670C2F4
            data: [4096 bits]
    :encrypted data packet:
            length: unknown
            mdc_method: 2
    gpg: encrypted with 4096-bit RSA key, ID 0x249C32A6B670C2F4, created 2014-08-08
          "Chris Belcher <false@email.com>"
    gpg: decryption failed: secret key not available

But anyway, yes I'll just post the logs here give me a moment.

**Comment by tailsjoin** [comment]
I don't have this log anymore. If it happens again I'll get it to you.

**Comment by tailsjoin** [comment]
New error with this branch:

    File tumbler.py, line 351, in main
        irc.run()
      File /home/amnesia/joinmarket/lib/irc.py, line 492, in run
        self.__handle_line(line)
      File /home/amnesia/joinmarket/lib/irc.py, line 395, in __handle_line
        self.__handle_privmsg(chunks[0], chunks[2], get_irc_text(line))
      File /home/amnesia/joinmarket/lib/irc.py, line 333, in __handle_privmsg
        box = self.__get_encryption_box(self.built_privmsg[nick][0], nick)
      File /home/amnesia/joinmarket/lib/irc.py, line 307, in __get_encryption_box
        return self.cjpeer.get_crypto_box_from_nick(nick)
      File /home/amnesia/joinmarket/lib/taker.py, line 355, in get_crypto_box_from_nick
        return self.cjtx.crypto_boxes[nick][1] #libsodium encryption object
    KeyError: 'gunter2bot'
    
    done

Here's a couple logs:

* https://gist.github.com/anonymous/ad7c4935a44efa06de2d

* https://gist.github.com/anonymous/441c0f19692daa15042b

**Comment by chris-belcher** [comment]
During the second log the IRC connection disconnects, when it reconnects a second TumblerThread is started. So there were two tumbler processes going on at the same time, using some of the same resources. I haven't looked in detail but thats probably the reason. Ultimately it errored the same as the first one.

For the first one, I can't seem to find the reason. We don't have enough information from the dump. It's confusing as hell.

A lot of this is now testing the tumbler as well as the taker recovery patch, never before has the tumbler had the chance to actually work and recover from nonresponse.

Added a commit. I'll my running my own tumbler instance too at some point. There's way more bugs around here.

**Comment by chris-belcher** [comment]
With the last commit, I ran tumbler with 11 txes and it worked successfuly. It correctly handled an nonresponsive maker at one point.

I'll run something longer now. I'm assuming its working alright for you people too, since nobody is posting any error logs. We could probably merge this pretty soon.

**Comment by chris-belcher** [comment]
No wonder nobody could get the tumbler to run all the way through I'm fixing a ton of bugs here.

**Comment by tailsjoin** [comment]
Here's a log which has the error above about the "libsodium encryption object" and some threading error right after it. The threading error I've been seeing on multiple tumble sessions, but it doesn't usually have a negative effect so I didn't mention yet.

https://gist.github.com/anonymous/283d5dffe6f9d6c9b0bb

**Comment by chris-belcher** [comment]
I've found the cause of that bug and the one on 15/9/2015
A maker did not respond in time so your tumbler went into the timeout sequence, trouble is the nonresponsive maker then actually responded.

A whole new coinjointx object is created in an effort to recover from timeout, which overwrites all the crypto_box objects then when the old maker actually replies the crypto_box object isnt there, so it crashes.

**Comment by AdamISZ** [comment]
@chris-belcher  Wrt 8be8c5c : I already fixed that in https://github.com/chris-belcher/joinmarket/pull/186/files#diff-7dca4cc17829f93a2517b5a8dd3ef018L151 . Not sure why you didn't have it?

**Comment by chris-belcher** [comment]
I rewrote parts of tumbler to make them benefit from taker recovery from maker timeout. So I must've reintroduced the bug.

**Comment by chris-belcher** [comment]
Managed to complete a long tumbler run of 38 transactions without crashing or error. It correctly recovered from a nonresponsive maker. All the bugs I know of are fixed.

Someone else try this, it's near finished.

**Comment by tailsjoin** [comment]
>Do you think it might be useful to add automatic increasing of maker_timeout_sec to your tails scripts?

Yes, I'm doing all of my testing on Tails w/blockr in a VM behind a VPN.  So I don't think anyone should have more more lag than that. I had my first successful session already with the current code, so now just a little more testing and I'll check the timestamps to see how to set the default there.

**Comment by chris-belcher** [comment]
> I had my first successful session already with the current code,

Excellent news.

There's little downside to setting the timeout too long for the tumbler script, since users will usually be setting it and walking away.

For integration with wallets when people will be waiting might be another thing. Also remember that some makers who respond too slowly might deserve to be canceled and blacklisted.

**Pull request merged**
