### PR TITLE
Use HTTPS rather than HTTP

### LINKED ISSUE #264: Use HTTPS for API calls
Use HTTPS calls for blockchian, blockr.io, etc. inside:

> lib/blockchaininterface.py
> lib/bitcoin/bci.py

### PR DESCRIPTION
**Pull request by ande2101**
Use HTTPS rather than HTTP for API calls to blockr.io and blockchain.info

Fixes #264

### CODE REVIEW

**Comment by chris-belcher** [comment]
So has anyone tried this yet?

I remember doing something like this many months ago but seem to remember it didn't work. Also you should all know the python urllib library doesn't check the SSL certificate.

**Comment by ande2101** [comment]
I've been running yield-generator for a few days now and that seems okay. My failures are now related to DNS and connection issues to IRC, I haven't seen issue #263 since so it must have been a naughty exit node. Also the SSL certs are checked as of [Python 2.7.9](https://www.python.org/downloads/release/python-279/)

I haven't done a shared send or run the tumble script, mostly because I'm cheap. I did check that the HTTPS addresses worked though.

**Comment by chris-belcher** [comment]
The IRC network has an onion so you don't have to go through exit nodes.

Has your yield generator done any successful joins?

**Comment by ande2101** [comment]
Yep I've successfully done joins using this, also I've removed the other commits.

Cheers

Ande

**Pull request merged**
