### PR TITLE
Implemented socks5 proxy

### PR DESCRIPTION
**Pull request by abitfan**
Socks5 proxy support as per #63

### CODE REVIEW

**Comment by abitfan** [comment]
This doesn't support .onion sites yet

**Comment by chris-belcher** [comment]
It actually does work with .onions

I just tried it with another IRC onion and it works. The problem is the snoonet onion is down, I confirmed it asking in #snoonet, they do plan to get it back up in time.

Tested it, seems to work. Will merge.

**Comment by BitpopCoin** [comment]
Beautiful work

**Comment by BitpopCoin** [comment]
Tor may cause more disconnects

https://github.com/chris-belcher/joinmarket/issues/34

https://github.com/chris-belcher/joinmarket/issues/21

**Comment by chris-belcher** [comment]
@BippopCoin what do you mean by linking those other issues? Please explain why they're relevant, I don't understand.

**Comment by BitpopCoin** [comment]
I think those issues relate to disconnects and issues that occur after

**Comment by chris-belcher** [comment]
@abitfan please get in touch: belcher@riseup.net or the IRC channel

**Comment by BitpopCoin** [comment]
Can this be added to blockr?

**Comment by BitpopCoin** [comment]
Guys are you sure this works? For me it's working using any port which means it's not really using the proxy.

**Comment by abitfan** [comment]
I get ProxyConnectionError(), as expected, when using a non socks port.
So far I'm connecting successfully with non-tor socks but with tor I still haven't managed to connect and its a pita to test due to servers being down, refusing tor connections or meaningless errors which are hard to hunt down. I will eventually setup a tor irc server to get this finished.
When you are enabling socks you need to disable ssl for it to properly work, as the ssl wrapping is causing some problems.

**Comment by chris-belcher** [comment]
When I was testing I found a working irc onion on reddit.com/r/onions I think, or maybe it was the hidden wiki.

It worked for me. The socks protocol that tor uses is the same as any other socks protocol, no reason it shouldn't work for both.

**Comment by abitfan** [comment]
True. I made the difference because with tor you have to be extra careful to redirect dns requests through tor as well. Initially when I first implemented it debugging this took me the most time.

**Comment by chris-belcher** [comment]
Connecting to an onion proves the DNS redirection works, because regular DNS doesn't understand the .onion TLD

**Comment by BitpopCoin** [comment]
Look at the port, this isn't possible unless I'm an idiot? 

13 10:39:12] starting irc                                         
[2015/05/13 10:39:12] connecting                                           
[2015/05/13 10:39:12] Using socks5 proxy 127.0.0.1:80085                   
[2015/05/13 10:39:14] >>pubmsg !orderbook                                  
[2015/05/13 10:39:14] Connected to IRC and joined channel                  
waiting for all orders to certainly arrive

**Comment by chris-belcher** [comment]
Yes port numbers only go up to 65535 or so.

Thats from here https://github.com/chris-belcher/joinmarket/blob/master/lib/irc.py#L455

Looks like the format string uses %s:%s when it should be %s:%d, easy fix. And doesn't affect the actual proxying.

**Pull request merged**
