### PR TITLE
default tor socks5_port consistency

### PR DESCRIPTION
**Pull request by CohibAA**
See https://github.com/chris-belcher/joinmarket/pull/182

### CODE REVIEW

**Comment by CohibAA** [comment]
Also, do/will test scripts use freenode (without ssl)?

**Comment by AdamISZ** [comment]
@CohibAA in the test/ directory there's a sample joinmarket.cfg, but you can edit the IRC settings to anything you like. If that's what you were asking?

**Comment by CohibAA** [comment]
@AdamISZ No, I mean that in the current master test directory, the regtest_joinmarket.cfg (https://github.com/chris-belcher/joinmarket/blob/master/test/regtest_joinmarket.cfg) shows irc.freenode.net on a #joinmarket-pit channel.  I am curious if this should be updated to match the current IRC channel, or if the tests have some dependency on freenode IRC instead.

**Comment by AdamISZ** [comment]
I guess the best I can say is - for ssl, sure, it should probably be set as default, including in the basic regtest. I will try that now (perhaps you already have).

Re; the channel, yes, as the wiki says, set it to anything you like, but remember about the -test suffix.

I don't think you can run the tests on cyberguerrilla because you're only allowed 2 (or 3?) connections. And I don't know if you can use a tor connection on freenode(?) I didn't pay attention to those aspects, but for sure I'd be interested to know if you can do it. It would clearly be a good thing if we can run tests via tor as well as clearnet.

**Comment by AdamISZ** [comment]
@CohibAA I just ran a regtest.py with port 6697 and use_ssl=True on freenode and it was OK. So maybe add this to the PR, as well as whatever else you discover. No reason not to use ssl by default I think.

**Comment by tailsjoin** [comment]
https://freenode.net/irc_servers.shtml#tor

**Comment by CohibAA** [comment]
Freenode default SSL settings updated per https://freenode.net/irc_servers.shtml#ssl

FYI regrading tor on freenode:
> https://freenode.net/irc_servers.shtml#tor
> Accessing freenode Via Tor
> *** PLEASE NOTE THAT THE tor HIDDEN SERVICE IS CURRENTLY UNAVAILABLE AND THERE IS NO SET DATE FOR ITS RETURN ***

**Comment by chris-belcher** [comment]
Needs a rebase

**Pull request closed without merging**
