### PR TITLE
use curl instead of wget for maximal portability

### PR DESCRIPTION
**Pull request by adlai**
see http://daniel.haxx.se/docs/curl-vs-wget.html for details

### CODE REVIEW

**Comment by tailsjoin** [comment]
Agreed.

**Comment by chris-belcher** [comment]
untested ACK

That commit code probably isnt portable to windows which doesnt have /dev/null

**Comment by adlai** [comment]
-s silences the progress updates, but curl still outputs the headers (from -I) to stdout. If portability trumps spam, we could leave them, and let each person customize complete silencing for their platform if necessary. I've also added the same timeout as the wget code.

**Comment by chris-belcher** [comment]
curl: option --connect-timeout: expected a proper numerical parameter

`--connect-timeout 1` seems to work. Trying this tonight.

**Comment by chris-belcher** [comment]
Seems to work well.

**Comment by chris-belcher** [comment]
edited the wiki to change wget to curl

**Pull request merged**
