### PR TITLE
unmask sybil counterparties by hostmask

### PR DESCRIPTION
**Pull request by adlai**
Working (tested) version of #311.

I'm not certain what caused the heisenbug with `IRCMessageChannel.__privmsg()`; the symptom was that it didn't strip hostmask, and didn't execute debug print statements when I tried to figure out why; yet print statements did indicate that it was running changed code. Makes me itch for modularization à la #254... any update from @ghtdak on regarding https://github.com/ghtdak/joinmarket/tree/master-refactor_v1 ?

### CODE REVIEW

**Comment by tailsjoin** [comment]
Maybe I don't understand this PR, but just on a quick check of the room `joinmarket-pit`:

    81 total
    22 users with the hostmask: CgAn-7g5.05e.aubm9g.IP

So it seems this is easier to fake, just use Tor?

**Comment by adlai** [comment]
@tailsjoin The ideal solution is being fleshed out in #287, this is a short-term fix which gives sybils an incentive to get new IPs. If the easiest way for them to do so is Tor, then that's what they'll do.

**Comment by tailsjoin** [comment]
Understood, thanks.

**Comment by adlai** [comment]
* commit message summarizes rationale
* fixed bug which was due to omission of stripping from `announce_orders`

**Pull request closed without merging**
