### PR TITLE
Timing fixes for large/multiparty transactions

### PR DESCRIPTION
**Pull request by adlai**
Tested with 16 parties.

### CODE REVIEW

**Comment by chris-belcher** [comment]
Looks good.

Is the line in taker.py fixing a race condition?

**Comment by adlai** [comment]
Yes, there appears to be a race to build the transaction before keys are received.

**Comment by chris-belcher** [comment]
I see, so it may happen that the taker sends !fill to several makers inside CoinJoinTX. The first maker responds with !pubkey before the CoinJoinTX method has returned and thus self.cjtx is null.

**Comment by adlai** [comment]
Rebased, added comments

**Comment by CohibAA** [comment]
I was recently kicked from the IRC channel (Orly? Whore!) as a taker using sendpayment while sending auths.  I was able to resolve by adding 

    time.sleep(1) #HACK! really there should be rate limiting, see issue#31

under [this line](https://github.com/chris-belcher/joinmarket/blob/master/lib/irc.py#L105).

Also, my maker was later kicked from IRC (Orly?) also while sending auths, so I added the same thing under [this line](https://github.com/chris-belcher/joinmarket/blob/master/lib/irc.py#L144) which seems to have resolved the kicks, afaict.

**Pull request closed without merging**
